SRCS=tlint.c macros.c symbol.c fonts.c
OBJS=tlint.o macros.o symbol.o fonts.o

tlint:$(OBJS)
        cc $(CFLAGS) -o tlint $(OBJS)

lint:
        lint -xh $(SRCS)

fonts.o: fonts.c gen.h symbol.h

macros.o: font.h gen.h macro.h macros.c symbol.h

symbol.o: symbol.c symbol.h

tlint.o: font.h gen.h macro.h tlint.c
