all : memory_locations m_and_p pointer_vars

m_locations : memory_locations.c	
	gcc memory_locations.c -o memory_locations
	
m_and_p : memory_n_pointers.c	
	gcc memory_n_pointers.c -o memory_n_pointers
	
pointer_vars : pointer-variables.c
	gcc pointer-variables.c -o pointer-variables